# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-03 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=50, verbose_name='\u8d44\u4ea7\u540d\u79f0')),
                ('ipaddr', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('cabinet_num', models.CharField(max_length=20, verbose_name='\u673a\u67dc\u7f16\u53f7')),
                ('run_service', models.CharField(max_length=50, verbose_name='\u8fd0\u884c\u670d\u52a1')),
                ('listen_port', models.CharField(max_length=50, verbose_name='\u76d1\u542c\u7aef\u53e3')),
                ('service_fact', models.CharField(max_length=50, verbose_name='\u670d\u52a1\u5668\u5382\u5bb6')),
                ('asset_memory', models.SmallIntegerField(null=True, verbose_name='\u8d44\u4ea7\u5185\u5b58')),
                ('cpu_type', models.SmallIntegerField(null=True, verbose_name='cpu\u578b\u53f7')),
                ('cpu_num', models.SmallIntegerField(null=True, verbose_name='\u7269\u7406cpu\u6570\u91cf')),
                ('hard_disk', models.CharField(max_length=20, null=True, verbose_name='\u786c\u76d8')),
                ('hostname', models.CharField(max_length=20, null=True, verbose_name='\u4e3b\u673a\u540d')),
                ('os_type', models.CharField(max_length=20, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('sn', models.CharField(max_length=20, null=True, verbose_name='\u5feb\u901f\u670d\u52a1\u7f16\u7801')),
                ('mac', models.CharField(max_length=48, null=True, verbose_name='mac\u5730\u5740')),
                ('ground_date', models.DateTimeField(verbose_name='\u4e0a\u67b6\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8d44\u4ea7\u540d\u79f0',
                'verbose_name_plural': '\u8d44\u4ea7\u540d\u79f0',
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('idc_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('idc_name', models.CharField(max_length=20, verbose_name='idc\u540d\u79f0')),
                ('idc_phone', models.CharField(max_length=11, verbose_name='idc\u8054\u7cfb\u4eba\u7535\u8bdd')),
                ('idc_username', models.CharField(max_length=50, verbose_name='idc\u8054\u7cfb\u4eba')),
                ('idc_addr', models.CharField(max_length=50, null=True, verbose_name='idc\u5730\u5740')),
                ('comments', models.CharField(max_length=100, null=True, verbose_name='\u5907\u6ce8')),
                ('update_date', models.DateTimeField(null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'idc\u5730\u5740',
                'verbose_name_plural': 'idc\u5730\u5740',
            },
        ),
        migrations.CreateModel(
            name='Maintains',
            fields=[
                ('maintain_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('record', models.CharField(max_length=200, verbose_name='\u7ef4\u62a4\u8bb0\u5f55')),
                ('comments', models.CharField(max_length=100, verbose_name='\u5907\u6ce8')),
                ('maintain_date', models.DateTimeField(verbose_name='\u7ef4\u62a4\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7ef4\u62a4\u8bb0\u5f55',
                'verbose_name_plural': '\u7ef4\u62a4\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Ribao',
            fields=[
                ('ribao_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('ribao_type', models.CharField(max_length=50, verbose_name='\u65e5\u62a5\u7c7b\u578b')),
                ('work_date', models.DateTimeField(verbose_name='\u5de5\u4f5c\u65f6\u95f4')),
                ('work_content', models.CharField(max_length=500, verbose_name='\u5de5\u4f5c\u5185\u5bb9')),
                ('use_time', models.SmallIntegerField(verbose_name='\u5de5\u4f5c\u65f6\u957f')),
                ('solve', models.CharField(max_length=50, verbose_name='\u89e3\u51b3\u65b9\u6cd5')),
                ('commit_date', models.DateTimeField(verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6807\u9898',
                'verbose_name_plural': '\u6807\u9898',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, verbose_name='\u89d2\u8272\u540d')),
                ('role_realname', models.CharField(max_length=50, verbose_name='\u89d2\u8272\u5b9e\u540d')),
                ('comments', models.CharField(max_length=50, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u89d2\u8272\u540d',
                'verbose_name_plural': '\u89d2\u8272\u540d',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='\u7528\u6237\u540d')),
                ('realname', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
                ('user_passwd', models.CharField(max_length=50, verbose_name='\u767b\u9646\u5bc6\u7801')),
                ('phone', models.CharField(max_length=11, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('email', models.EmailField(max_length=254, verbose_name='\u7535\u5b50\u90ae\u4ef6')),
                ('isactive', models.BooleanField(verbose_name='\u662f\u5426\u6fc0\u6d3b')),
                ('reg_date', models.DateTimeField(verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('last_login_date', models.DateTimeField(verbose_name='\u6700\u540e\u767b\u5f55\u65f6\u95f4')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Roles', verbose_name='\u89d2\u8272\u7f16\u53f7')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u540d',
                'verbose_name_plural': '\u7528\u6237\u540d',
            },
        ),
        migrations.AddField(
            model_name='ribao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Users', verbose_name='\u7528\u6237\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='asset',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Idc', verbose_name='\u673a\u623f\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Users', verbose_name='\u7528\u6237\u7f16\u53f7'),
        ),
    ]
