# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-03 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={'verbose_name': 'idc\u540d\u79f0', 'verbose_name_plural': 'idc\u540d\u79f0'},
        ),
    ]
