# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-03 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20170303_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ribao',
            options={'verbose_name': '\u65e5\u62a5\u6807\u9898', 'verbose_name_plural': '\u65e5\u62a5\u6807\u9898'},
        ),
        migrations.AlterField(
            model_name='ribao',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u65e5\u62a5\u6807\u9898'),
        ),
    ]
