# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-03 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_idc_maintains_ribao_roles_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_memory',
            field=models.SmallIntegerField(null=True, verbose_name='\u8d44\u4ea7\u5185\u5b58'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cpu_num',
            field=models.SmallIntegerField(null=True, verbose_name='\u7269\u7406cpu\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cpu_type',
            field=models.SmallIntegerField(null=True, verbose_name='cpu\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hard_disk',
            field=models.CharField(max_length=20, null=True, verbose_name='\u786c\u76d8'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(max_length=20, null=True, verbose_name='\u4e3b\u673a\u540d'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='mac',
            field=models.CharField(max_length=48, null=True, verbose_name='mac\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os_type',
            field=models.CharField(max_length=20, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sn',
            field=models.CharField(max_length=20, null=True, verbose_name='\u5feb\u901f\u670d\u52a1\u7f16\u7801'),
        ),
    ]
