# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-03 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20170303_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='id',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
